plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.192'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = proj_version
group = group_id

base {
    archivesName = proj_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : proj_id,
                'Specification-Vendor'    : authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'FMLModType'              : 'GAMELIBRARY'
        ])
    }
}

java {
	withSourcesJar()
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
        	group = authors
        	artifactId = "${proj_id}-neoforge"
            artifact jar
            artifact sourcesJar
        }
    }
    repositories {
        maven {
		    name "nonamecrackers2Maven"
		    url "https://maven.nonamecrackers2.dev/${maven_dir}"
		    credentials(PasswordCredentials)
		    authentication {
		    	basic(BasicAuthentication)
		    }
		}
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}